apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: lg-guestbook
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/dhpup/listgen.git
          revision: main
          files:
          - path: src/listgen/configs/clusters.yaml
      - list:
          elementsYaml: "{{ .cluster.list | toJson }}"
  template:
    metadata: 
      name: "listgen-{{.namespace}}"
    spec:
      project: listgen
      source:
        repoURL: https://github.com/dhpup/listgen.git
        targetRevision: main
        path: guestbook/stages/{{.namespace}}
      destination:
        server: "{{.name}}"
        namespace: "{{.namespace}}"
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
        - CreateNamespace=true